name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - notebook
  - ipython
  - gspread
  - ipywidgets
  - numpy 
  - pandas 
  - voila
  - st-excel-table==0.1.6
  - nbgitpuller 
  - pip
  - pip:
      - python-dotenv

