name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - notebook
  - ipython
  - gspread
  - ipywidgets
  - numpy 
  - pandas 
  - voila
  - nbgitpuller 
  - pip
  - pip:
      - python-dotenv
  - yt-dlp>=2025.11.7
  - tqdm>=4.65.0
