name: myenv
channels:
  - conda-forge
dependencies:
  - python
  - notebook
  - ipython
  - streamlit
  - gspread
  - google-auth
  - st-excel-table
  - ipywidgets
  - numpy 
  - pandas 
  - voila
  - nbgitpuller 
  - pip
  - pip:
      - python-dotenv

