name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - notebook
  - ipython
  - streamlit==1.30.0
  - pandas==2.1.0
  - gspread==5.7.2
  - google-auth==2.23.0
  - st-excel-table==0.1.2
  - ipywidgets
  - numpy 
  - pandas 
  - voila
  - nbgitpuller 
  - pip
  - pip:
      - python-dotenv

